---
title: Federico Zerbini
timezone: Europe/Paris
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: false
    social-share: false
- scope:
    path: ''
  values:
    layout: page
    show-avatar: false
url: http://federicozerbini.github.io
baseurl: 
description: Ph.D in Mathematics
navbar-links:
  About: aboutme
  Publications: publications
  Next Events: nextevents
avatar: "/img/avatar-icon.png"
author:
  name: Federico Zerbini
  email: zerbini.federico@gmail.com
  facebook: mathemagician
  github: yourname
  twitter: mathemagician
  reddit: yourname
  google-plus: "+yourname"
  linkedin: mathemagician
  xing: yourname
  stackoverflow: yourlink
  snapchat: yourname
  instagram: yourname
  youtube: yourlink
  spotify: yourname
  telephone: yourphone
  steam: yourname
  twitch: yourname
  yelp: yourname
footer-links-active:
  rss: false
  facebook: false
  email: true
  twitter: false
  google-plus: false
  github: false
  reddit: false
  linkedin: false
  xing: false
  stackoverflow: false
  snapchat: false
  instagram: false
  youtube: false
  spotify: false
  telephone: false
  steam: false
  twitch: false
  yelp: false
share-links-active:
  twitter: false
  facebook: false
  google: false
  linkedin: false
excerpt_length: 50
title-separator: "-"
markdown: kramdown
highlighter: rouge
permalink: "/:title/"
paginate: 5
kramdown:
  input: GFM
link-tags: false
exclude:
- CHANGELOG.md
- CNAME
- Dockerfile
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- Vagrantfile
prose:
  rooturl: _posts
  media: img
  ignore:
  - 404.html
  - LICENSE
  - feed.xml
  - _config.yml
  - "/_layouts"
  - "/_includes"
  - "/css"
  - "/img"
  - "/js"
  metadata:
    _posts:
    - name: layout
      field:
        element: hidden
        value: post
    - name: title
      field:
        element: text
        label: Post title
        placeholder: Title
        alterable: true
    - name: subtitle
      field:
        element: textarea
        label: Subtitle
        placeholder: A description of your post.
        alterable: true
    - name: date
      field:
        element: text
        label: Date
        help: Enter date of post.
        placeholder: yyyy-mm-dd
        alterable: true
    - name: image
      field:
        element: text
        label: Image
        help: Add a thumbnail image to your post.
        placeholder: Thumbnail
        alterable: true
    - name: published
      field:
        element: checkbox
        label: Publish
        help: Check to publish post, uncheck to hide.
plugins:
- jekyll-paginate
